"""create resume tables"""

revision = 'f8ed9f77d689'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_resumes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_resumes_created_at'), 'master_resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_master_resumes_name'), 'master_resumes', ['name'], unique=False)
    op.create_index(op.f('ix_master_resumes_target_role'), 'master_resumes', ['target_role'], unique=False)
    op.create_index(op.f('ix_master_resumes_updated_at'), 'master_resumes', ['updated_at'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_keywords', sa.JSON(), nullable=True),
    sa.Column('tailored_resume', sa.JSON(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('ats_overall_score', sa.Integer(), nullable=True),
    sa.Column('ats_keyword_coverage', sa.Float(), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_ats_overall_score'), 'tailored_resumes', ['ats_overall_score'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_company'), 'tailored_resumes', ['company'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_created_at'), 'tailored_resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_job_title'), 'tailored_resumes', ['job_title'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_profile'), 'tailored_resumes', ['profile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_profile'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_title'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_created_at'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_company'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_ats_overall_score'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_master_resumes_updated_at'), table_name='master_resumes')
    op.drop_index(op.f('ix_master_resumes_target_role'), table_name='master_resumes')
    op.drop_index(op.f('ix_master_resumes_name'), table_name='master_resumes')
    op.drop_index(op.f('ix_master_resumes_created_at'), table_name='master_resumes')
    op.drop_table('master_resumes')
    # ### end Alembic commands ###
